export const ROUTES = {
    HOME: '/',
    // Routes Backoffice
    DASHBOARD: '/dashboard',
    AGENTS: '/agents',
    PARCELS: '/parcels',
    SIMPLE_RATES: '/simple-rates',
    GROUPED_RATES: '/grouped-rates',
    ZONE_CONFIGURATION: '/zone-configuration',
    AGENCE_PARTENAIRE: '/agence-partenaire',
    AGENCE_DETAIL: '/agence-partenaire/:id',
    PRODUITS: '/produits',
    BACKOFFICE_SETUP: '/backoffice-setup',
    PROFILE: '/profile',
    PARCEL_CONTROL: '/parcels/control/:code',
    PARCEL_HISTORY: '/parcels-history',
    INCOMING_PARCELS: '/incoming-parcels',
    COMPTABILITE: '/comptabilite',
    HISTORIQUE: '/historique',
};
